name: "Trigger Dev Deploy Workflow"

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch to trigger the deployment (default: dev)"
        default: "dev"
        required: false

jobs:
  trigger_dev_deploy:
    name: Trigger [DEV] Deploy Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Repository Dispatch
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.rest.repos.createDispatchEvent({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  event_type: "b1",
                  client_payload: {
                    branch: "${{ github.event.inputs.branch_name }}"
                  }
                });
                console.log(`Successfully triggered workflow: b1 . Response status: ${response.status}`);
            });
