name: Master Prod Workflow

on:
  workflow_dispatch:
    inputs:
      bu:
        description: 'Select the BU(s) to trigger'
        required: true
        type: choice
        options:
          - b1
          - b2
          - both

jobs:
  parse-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Define Workflow Mapping
        id: define-mapping
        run: |
          # Hardcoded mapping of BUs to workflow filenames
          echo "b1=b1-s1.yaml" >> mapping.txt
          echo "b1c1=b1-c1.yaml" >> mapping.txt
          echo "b2=b2-s1.yaml" >> mapping.txt
          echo "b2c1=b2-c1.yaml" >> mapping.txt

      - name: Parse BU Input
        id: parse-input
        run: |
          echo "Selected BU: ${{ github.event.inputs.bu }}"
          echo "${{ github.event.inputs.bu }}" > selected_bu.txt

      - name: Trigger Workflows Based on Selection
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');

            // Read the selected service from input
            const selectedBu = fs.readFileSync('selected_bu.txt', 'utf8').trim();

            // Read workflow mappings
            const mappings = {};
            const mappingLines = fs.readFileSync('mapping.txt', 'utf8').split('\n').filter(line => line.trim());
            mappingLines.forEach(line => {
              const [key, value] = line.split('=');
              mappings[key.trim()] = value.trim();
            });

            // Define workflows to trigger based on input
            const workflowsToTrigger = [];
            if (selectedBu === 'b1' || selectedBu === 'both') {
              workflowsToTrigger.push(mappings['b1s1'], mappings['b1c1']);
            }
            if (selectedBu === 'b2' || selectedBu === 'both') {
              workflowsToTrigger.push(mappings['b2s1'], mappings['b2c1']);
            }

            // Trigger workflows in parallel
            const branch = 'main'; // Adjust this if branch input is needed
            const promises = workflowsToTrigger.map(workflowFile => {
              console.log(`Triggering workflow: ${workflowFile}`);
              return github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: workflowFile,
                ref: branch,
              });
            });

            // Wait for all workflows to be dispatched
            await Promise.all(promises);
            console.log('All workflows triggered successfully.');
