name: "Trigger Dev Deploy Workflow"

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch to trigger the deployment (default: dev)"
        default: "dev"
        required: false

jobs:
  trigger_dev_deploy:
    name: Trigger [DEV] Deploy Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Repository Dispatch
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branchName = "${{ inputs.branch_name }}" || "dev";
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: "b1", // Must match the event type in the target workflow
              client_payload: {
                branch: branchName
              }
            });
