name: Dynamic Consumer Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      bu:
        description: 'Select BU (e.g., adb, qoala, both, none)'
        required: true
        default: 'none'
      consumers:
        description: 'Select Consumers (e.g., b1c1, b2c1, both, none)'
        required: true
        default: 'none'
      branch:
        description: 'Specify the branch (e.g., main, develop, etc.)'
        required: true
        default: 'main'

jobs:
  parse-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Define Workflow Mapping
        id: define-mapping
        run: |
          # Define mappings for BUs and their workflows
          echo "b1=b1-s1.yaml" >> mapping.txt
          echo "b1 c1=b1-c1.yaml" >> mapping.txt
          echo "b2=b2-s1.yaml" >> mapping.txt
          echo "b2 c1=b2-c1.yaml" >> mapping.txt

      - name: Save Selected BU and Consumers
        id: save-inputs
        run: |
          echo "${{ github.event.inputs.bu }}" > selected_bu.txt
          echo "${{ github.event.inputs.consumers }}" > selected_consumers.txt
          echo "${{ github.event.inputs.branch }}" > selected_branch.txt

      - name: Trigger Workflows Based on Selection
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');

            // Read the selected BU, Consumers, and Branch from input
            const selectedBu = fs.readFileSync('selected_bu.txt', 'utf8').trim();
            const selectedConsumers = fs.readFileSync('selected_consumers.txt', 'utf8').trim();
            const selectedBranch = fs.readFileSync('selected_branch.txt', 'utf8').trim();

            // Read workflow mappings
            const mappings = {};
            const mappingLines = fs.readFileSync('mapping.txt', 'utf8').split('\n').filter(line => line.trim());
            mappingLines.forEach(line => {
              const [key, value] = line.split('=');
              mappings[key.trim()] = value.trim();
            });

            // Define workflows to trigger based on inputs
            const workflowsToTrigger = [];

            // Handle BU workflows
            if (selectedBu === 'b1' || selectedBu === 'both') {
              workflowsToTrigger.push(mappings['b1']);
            }
            if (selectedBu === 'b2' || selectedBu === 'both') {
              workflowsToTrigger.push(mappings['b2']);
            }

            // Handle Consumer workflows
            if (selectedConsumers === 'b1 c1' || selectedConsumers === 'both') {
              workflowsToTrigger.push(mappings['b1 c1']);
            }
            if (selectedConsumers === 'b2 c1' || selectedConsumers === 'both') {
              workflowsToTrigger.push(mappings['b2 c1']);
            }

            // Log workflows to trigger
            console.log('Workflows to Trigger:', workflowsToTrigger);

            // Trigger workflows in parallel
            const promises = workflowsToTrigger.map(workflowFile => {
              console.log(`Triggering workflow: ${workflowFile} on branch: ${selectedBranch}`);
              return github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: workflowFile,
                ref: selectedBranch, // Use the selected branch from input
              });
            });

            // Wait for all workflows to be dispatched
            await Promise.all(promises);
            console.log('All workflows triggered successfully.');
        env:
          INPUT_BU: ${{ github.event.inputs.bu }}
          INPUT_CONSUMERS: ${{ github.event.inputs.consumers }}
          INPUT_BRANCH: ${{ github.event.inputs.branch }}